apiVersion: v1
kind: Service
metadata:
  name: fashionme-db
spec:
  type: NodePort
  selector:
    app: fashionme-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashionme-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashionme-db
  template:
    metadata:
      labels:
        app: fashionme-db
    spec:
      containers:
      - name: fashionme-db
        image: jayanisathukorala/fashionme-db:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: shared-storage
          mountPath: /var/lib/postgresql/data
          subPath: db-data  # Store database files in a separate directory within the volume
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: postgres-pvc  # Correct reference
