apiVersion: v1
kind: Service
metadata:
  name: home-service
spec:
  selector:
    app: home-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-service
  template:
    metadata:
      labels:
        app: home-service
    spec:
      containers:
      - name: home-service
        image: jayanisathukorala/home-service:latest
        ports:
        - containerPort: 5002
        
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: fashionme.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-service
            port:
              number: 80
      - path: /home(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: home-service
            port:
              number: 80
