apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: jayanisathukorala/product-service:latest
        ports:
        - containerPort: 5003
        volumeMounts:        # Place this inside the container definition
        - name: shared-storage
          mountPath: /shared-data  # Mounting path in the container
      volumes:               # Place this at the spec.template.spec level
      - name: shared-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: fashionme.com
    http:
      paths:
      - path: /product(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 80
