apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
spec:
  selector:
    app: user-auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth-service
  template:
    metadata:
      labels:
        app: user-auth-service
    spec:
      containers:
      - name: user-auth-service
        image: jayanisathukorala/user-auth-service:latest
        ports:
        - containerPort: 5001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: fashionme.com
    http:
      paths:
      - path: /auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-auth-service
            port:
              number: 80

